name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Specify the Node.js version explicitly
    defaults:
      run:
        shell: bash
        working-directory: ./dist
        # Specify the Node.js version explicitly
        node-version: '20.x'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

      # Install Python (assuming Python is not available on macOS runner)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm install numpy # Replace with the necessary dependencies

      # Generate the snake
      - name: Generate Snake
        run: python generate_snake.py

      # Show the status of the build. Makes it easier for debugging (if there are any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Assuming you want to deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
